version: "3.9"
services:
  db:
    container_name: db_tamplate_container
    image: postgres:13.3
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/migrations/001_init_tables.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - postgres

  tgbot:
    build:
      context: ./
      dockerfile: ./tgbot/Dockerfile
    container_name: tgbot
    command: python -m tgbot
    volumes:
      - .:/tg_app
    working_dir: /tg_app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - postgres


networks:
  postgres:
    driver: bridge